### ISSUE TITLE
Port to improved-base

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs-jquery#12]
I put in some of the work to port this to improved-base, but I need to switch gears, so I put up my WIP branch here: https://github.com/mgsloan/ghcjs-jquery/tree/improved-base

If anyone wants to carry this branch forward, let me know here!  I'll hopefully revisit this in a week or two.

**Comment by bergey** [comment]
@mgsloan This is done now, right?

**Comment by mgsloan** [comment]
Yup!
