### ISSUE TITLE
Why there is no "ready" function?

### ISSUE THREAD

**Issue by adinapoli** [ghcjs/ghcjs-jquery#14]
(cc @mgsloan )

Hey folks,

I was just wondering how come there is no [ready](https://api.jquery.com/ready/) FFI binding. Is this something automatically enforced by GHCJS or it's just an oversight?

Thanks a ton!

A.

**Comment by mgsloan** [comment]
I think it's likely just an oversight.  The JQuery bindings are certainly not complete.

I don't think that the invocation of `main` guarantees that the DOM is ready.  It might, but it'd surprise me if GHCJS did this.

**Comment by bergey** [comment]
In the HTML generated by GHCJS, I see

```
  <script language="javascript" src="runmain.js" defer></script>
```

I believe the `defer`, and the location of the `script` tag after the body, should be enough in most (all?) cases.

**Comment by mgsloan** [comment]
Indeed, but the generated HTML isn't always used, so your `main` could be invoked before the DOM is ready.

**Comment by adinapoli** [comment]
Thanks for the reply folks, I'm cooking a PR as we talk.

**Comment by adinapoli** [comment]
Argh, I started yak shaving to improve the state of `example/Main.hs` as [the porting to improved-base broke it](https://github.com/ghcjs/ghcjs-jquery/commit/42c5e2a5217603694c2bdac7ecf555bb5907a611#diff-398e4197be26d98b9a72b91f9a6643e7R338) but I stumbled upon other issues and now is work time. I will take another stab at if either after work or tomorrow!
